globals:
  session_name: user
  lang: es
  salt: yjlm
  paths:
    upload: 'uploads'
  csv:
    date_format: '%m/%d/%Y %H:%M %z'
    time_format: '%H:%M %z'
development:
  scope: ''
production:
  scope: ''